version: '3'

services:
  app:
    container_name: kyle-gpt-app
    build: .
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    networks:
      - hofi_network

networks:
  hofi_network:
    external: true

