version: '3'

services:
  app:
    container_name: kyle-gpt-app
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"

    networks:
      - hofi_network

networks:
  hofi_network:
    external: true

